runner_module: runners - ASD_Runner
random_seed: 111
params:
  epochs: 100
  device: cuda:1
  batch_size: 1
  latent_dim: 5
  image_size: 256
  nu: 0.1
  warm_up_n_iters: 100
  change_center: true
  embedding_num: 538000
  loss_ratio: 1, 1, 1

model:
  name: models - ASD_Encoder
  args:
    pH: 15
    pW: 15
    imH: ${params.image_size}
    imW: ${params.image_size}
    latent_dim: ${params.latent_dim}
    scales: 0.5, 1.0, 2.0
    device: ${params.device}
    first_channel: 14
  ckpt_dir: ''
  R: 3.0

transforms:
  train:
  - name: albumentations - ToFloat
    args:
      max_value: 3.10573988, 19.76154895, 31.55182958, 33.16014988, 9.97277588, 4.14412006, 3.69253086, 8.31289067, 3.54856272, 21.44150144, 5.78644177, 19.66132287, 4.04094509, 5.1214272
  - name: albumentations - Resize
    args:
      height: ${params.image_size}
      width: ${params.image_size}
      p: 1
  - name: albumentations - Normalize
    args:
      mean: 0.29806232, 0.04669171, 0.03023942, 0.02893952, 0.10255817, 0.25158816, 0.2805241,  0.12591956, 0.32969443, 0.05473487, 0.18137178, 0.05274475, 0.3096078, 0.32208666
      std: 0.0453959, 0.01116803, 0.01009212, 0.01726092, 0.04613517, 0.10774629, 0.12595032, 0.05952743, 0.14465308, 0.03188014, 0.09198966, 0.03371084, 0.16787375, 0.20945558
      max_pixel_value: 1.0 
  - name: albumentations.pytorch - ToTensorV2
    args:
      p: 1
  test:
  - name: albumentations - ToFloat
    args:
      max_value: 3.10573988, 19.76154895, 31.55182958, 33.16014988, 9.97277588, 4.14412006, 3.69253086, 8.31289067, 3.54856272, 21.44150144, 5.78644177, 19.66132287, 4.04094509, 5.1214272
  - name: albumentations - Resize
    args:
      height: ${params.image_size}
      width: ${params.image_size}
      p: 1
  - name: albumentations - Normalize
    args:
      mean: 0.29806232, 0.04669171, 0.03023942, 0.02893952, 0.10255817, 0.25158816, 0.2805241,  0.12591956, 0.32969443, 0.05473487, 0.18137178, 0.05274475, 0.3096078, 0.32208666
      std: 0.0453959, 0.01116803, 0.01009212, 0.01726092, 0.04613517, 0.10774629, 0.12595032, 0.05952743, 0.14465308, 0.03188014, 0.09198966, 0.03371084, 0.16787375, 0.20945558
      max_pixel_value: 1.0
  - name: albumentations.pytorch - ToTensorV2
    args:
      p: 1

datasets:
  train:
    name: datasets.landslide_dataset - LandSlideDataset
    args:
      img_dir: /data/ljt/land_slide_detection/train_images
      mask_dir: /data/ljt/land_slide_detection/train_labels
      is_training: true
      diversity_transform: true
      normal_id: '0'
  
  test:
    name: datasets.landslide_dataset - LandSlideDataset
    args:
      img_dir: /data/ljt/land_slide_detection/test_images
      is_training: false
      mask_dir: /data/ljt/land_slide_detection/test_labels
      normal_id: '0'
    
      
dataloaders:
  train:
    name: torch.utils.data - DataLoader
    args:
      batch_size: ${params.batch_size}
      num_workers: 3
      pin_memory: true
      shuffle: true
  test:
    name: torch.utils.data - DataLoader
    args:
      batch_size: ${params.batch_size}
      num_workers: 3
      pin_memory: true
      shuffle: false
optimizer:
  name: torch.optim - Adam
  args:
    lr: 1.0e-04
    weight_decay: 1.0e-05
scheduler:
  name: torch.optim.lr_scheduler - CosineAnnealingWarmRestarts
  args:
    T_0: 10
    T_mult: 2
    eta_min: 0.0001
    last_epoch: -1
criterions:
  MSE:
    name: torch.nn - MSELoss
    args: null